name: Build

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    runs-on: ${{ matrix.os }}
    outputs:
      version: ${{ steps.properties.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build release version
        run: cargo build --verbose --release --target=${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/main

  draft-release:
    name: Release Draft
    if: github.event_name != 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2.3.4

      - name: Remove Old Release Drafts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/releases \
            | tr '\r\n' ' ' \
            | jq '.[] | select(.draft == true) | .id' \
            | xargs -I '{}' \
          curl -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/releases/{}
      - name: Create Release
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "{ \"tag_name\": \"${{ github.ref }}\", \"target_commitish\": \"main\", \"name\": \"${{ github.ref }}\", \"body\": \"## Changelog\n- [ ]\", \"draft\":true }" \
            https://api.github.com/repos/${{ github.repository }}/releases
      - name: Save upload url of this draft release.
        run: |
          echo '${{ steps.create_draft_release.outputs.upload_url }}' > release_upload_url.txt
      - name: Upload `release_upload_url.txt`
        uses: actions/upload-artifact@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: draft-release
          path: release_upload_url.txt
  attach-assets-to-release:
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    needs: [build, draft-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: draft-release
      - id: upload-url
        run: |
          echo "url=$(cat draft-release/release_upload_url.txt)"
          echo "url=$(cat draft-release/release_upload_url.txt)" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v1
        with:
          name: build-${{ matrix.target }}
          path: build/
      - name: zip the artifact
        run: zip -j build/main.zip build/main
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.upload-url.outputs.url }}
          asset_path: ./build/main.zip
          asset_name: main-${{ matrix.target }}.zip
          asset_content_type: application/zip
